---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  security_group_ids: [ "<%= ENV['AWS_SGROUP_ID'] %>" ]
  region: us-west-2
  availability_zone: b
  instance_type: t2.micro
  associate_public_ip: true

transport:
  ssh_key: provision.key
  connection_timeout: 10
  connection_retries: 10

provisioner:
  name: salt_solo
  formula: consul
  salt_install: bootstrap
  salt_bootstrap_options: -P git v2015.8.7
  dependencies:
    - name: test-data
      path: .
  pillars-from-files:
    consul.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - consul

suites:
  - name: agent-install
    provisioner:
      state_top:
        base:
          '*':
            - consul.agent

  - name: agent-clean
    provisioner:
      state_top:
        base:
          '*':
            - consul.agent
            - test-data.agent.seed_clean

  - name: agent-remove
    provisioner:
      state_top:
        base:
          '*':
            - consul.agent
            - test-data.agent.seed_clean
            - consul.agent.remove

  - name: template-install
    provisioner:
      state_top:
        base:
          '*':
            - consul.agent
            - test-data.template.seed_kv
            - consul.template


  - name: template-clean
    provisioner:
      state_top:
        base:
          '*':
            - consul.agent
            - test-data.template.seed_kv
            - consul.template
            - test-data.template.seed_clean


  - name: template-remove
    provisioner:
      state_top:
        base:
          '*':
            - consul.agent
            - test-data.template.seed_kv
            - consul.template
            - test-data.template.seed_clean

platforms: 
  - name: ubuntu-precise
    transport:
      username: ubuntu
    driver:
      image_search:
        name: "ubuntu/images/hvm/ubuntu-precise-12.04-amd64-server-*"

  - name: ubuntu-trusty
    transport:
      username: ubuntu
    driver:
      image_search:
        name: "ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-*"

  - name: ubuntu-vivid
    transport:
      username: ubuntu
    driver:
      image_search:
        name: "ubuntu/images/hvm/ubuntu-vivid-15.04-amd64-server-*"

