---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile_local.erb

provisioner:
  name: salt_solo
  formula: consul
  salt_install: bootstrap
  salt_bootstrap_options: -P git v2015.8.7
  dependencies:
    - name: test-data
      path: .
  pillars-from-files:
    consul.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - consul

suites:
  - name: agent
    provisioner:
      state_top:
        base:
          '*':
            - consul.agent

  - name: template
    provisioner:
      state_top:
        base:
          '*':
            - consul.agent
            - consul.template

platforms:
  - name: debian-wheezy
    driver_config:
      box: debian/wheezy64
      box_url: https://atlas.hashicorp.com/debian/wheezy64

  - name: debian-jessie
    driver_config:
      box: debian/jessie64
      box_url: https://atlas.hashicorp.com/debian/jessie64
     
  - name: ubuntu-precise
    driver_config:
      box: ubuntu/precise64
      box_url: https://atlas.hashicorp.com/ubuntu/precise64

  - name: ubuntu-trusty
    driver_config:
      box: ubuntu/trusty64
      box_url: https://atlas.hashicorp.com/ubuntu/trusty64

  - name: ubuntu-vivid
    driver_config:
      box: ubuntu/vivid64
      box_url: https://atlas.hashicorp.com/ubuntu/vivid64

  - name: centos-6
    driver_config:
      box: bento/centos-6.7 
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-6.7

  - name: centos-7
    driver_config:
      box: centos/7
      box_url: https://atlas.hashicorp.com/centos/7


# issue with salt install on suse currently        
#  - name: suse-13
#    driver_config:
#      box: bento/opensuse-13.2
#      box_url: https://atlas.hashicorp.com/bento/opensuse-13.2
